# Generated by Django 3.1.1 on 2020-11-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_aboutme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
